@startuml
!include <C4/C4_Context>

!include Diagrams/Objects/People/Admin.puml
!include Diagrams/Objects/People/Expert.puml

!include Diagrams/Objects/Objects/Test1.puml
!include Diagrams/Objects/Objects/Test2.puml

!include Diagrams/Objects/Databases/CaseStudy.puml
!include Diagrams/Objects/Databases/ExpertUser.puml

title Admin

Rel(adminAlias,test1Alias,"Analyze Test Reports")
Rel(adminAlias,test2Alias,"Analyze Test Reports")
Rel(adminAlias,caseStudyDBAlias,"Modify Case Studies and Grading Criteria")
Rel(adminAlias, expertUserDBAlias," Maintain Profile and Security Info")
Rel(expertAlias, expertUserDBAlias," Add/Maintain Software Architects")

@enduml
